version: "3.9"
services:
  eureka-server:
    build: platform-services/discovery
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  one:
    build: business-services/one
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      server.port: 8081
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  two:
    build: business-services/two
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      server.port: 8082
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  common:
    build: business-services/common
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
    environment:
      server.port: 8000
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  feign:
    build: business-services/feign-api
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
    environment:
      server.port: 9000
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  apigateway:
    build: platform-services/apigateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      server.port: 8080
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
