server:
  port: 8090

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: two-id
          uri: http://localhost:8082
          predicates:
            - Path=/two/**
        - id: two-direct
          uri: http://localhost:8082
          predicates:
            - Path=/
        - id: one-direct
          uri: http://localhost:8081
          predicates:
            - Path=/greeting
        - id: akf
          uri: http://aki.nau.edu.ua
          predicates:
            - Path=/abiturient-2/
        - id: nau
          uri: https://nau.edu.ua
          predicates:
            - Path=/ua/info/10-prichin-chomu-nau/
        - id: shini
          uri: https://autoshini.com
          predicates:
            - Path=/podbor-shin
management:
  endpoints:
    web:
      exposure:
        include: "*"