server:
  port: 8090

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: two-id
          uri: http://localhost:8082
          predicates:
            - Path=/two/**
        - id: two-direct
          uri: http://localhost:8082
          predicates:
            - Path=/
        - id: one-direct
          uri: http://localhost:8081
          predicates:
            - Path=/greeting
management:
  endpoints:
    web:
      exposure:
        include: "*"