zuul:
  routes:
    two:
      path: /any/**
      url: http://localhost:8082/two
    direct:
      path: /**
      url: http://localhost:8082/
    nau:
      path: /nau/**
      url: https://nau.edu.ua
    akf:
      path: /akf/**
      url: https://nau.edu.ua/
    shina:
      path: /shina/**
      url: https://autoshini.com/
spring:
  application:
    name: zuul-server
server:
  port: 8062
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true