zuul:
  routes:
    two:
      path: /two/**
      url: http://localhost:8082/two
spring:
  application:
    name: zuul-server
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true